source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '>= 4.1.6'
gem 'mongoid'
gem 'bson_ext'
gem 'oj'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'httparty'
gem 'redis-rails'
gem 'bootstrap-sass'
gem 'haml_coffee_assets', github: 'netzpirat/haml_coffee_assets'
gem 'rails-assets-angular'
gem 'rails-assets-angular-route'
gem 'rails-assets-venturocket-angular-slider'
gem 'rails-assets-angular-ui-bootstrap-bower'
gem 'rails-assets-angular-cookies'
gem 'rails-assets-angulartics'
gem 'rails-assets-angular-ui-select'
gem 'rails-assets-angular-animate'
gem 'rails-assets-lazy.js'
gem 'newrelic_rpm'

group :development do
  gem 'spring'
  gem 'mysql2', require: false
  gem 'quiet_assets'
end
