# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fcd0290dafc8553b0d6cc2fd58fa62ae6110024faea05eb62be8d94495667b2e384435b052eed7c915188bc53151391afc1b940379e058ba3d26f6ea8508e17

test:
  secret_key_base: 47618f4f8c18a11543b7a2bda21fab1b30b3fbce664401b4b815b0a9052ec57cfa27f9a76d82fc3658724b93ee3226852609fb445c09daade5f3a5eb33b1ce08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
